services:
    _defaults:
        autowire: true
        autoconfigure: true

    Rf\ApiBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'